---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/users":
    get:
      summary: list users
      tags:
      - Users
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    surname:
                      type: string
                    email:
                      type: string
                    profession:
                      type: string
                    city:
                      type: string
                    country:
                      type: string
    post:
      summary: create user
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: created
        '422':
          description: unprocessable entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                surname:
                  type: string
                email:
                  type: string
                password:
                  type: string
                password_confirmation:
                  type: string
                profession:
                  type: string
                city:
                  type: string
                country:
                  type: string
              required:
              - name
              - surname
              - email
              - password
              - password_confirmation
  "/api/v1/users/{id}":
    get:
      summary: show user
      tags:
      - Users
      parameters:
      - name: id
        in: path
        description: ID de l'utilisateur
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  surname:
                    type: string
                  email:
                    type: string
                  profession:
                    type: string
                  city:
                    type: string
                  country:
                    type: string
        '404':
          description: not found
    put:
      summary: update user
      tags:
      - Users
      parameters:
      - name: id
        in: path
        description: ID de l'utilisateur
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: successful
        '404':
          description: not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                surname:
                  type: string
                email:
                  type: string
                profession:
                  type: string
                city:
                  type: string
                country:
                  type: string
    delete:
      summary: delete user
      tags:
      - Users
      parameters:
      - name: id
        in: path
        description: ID de l'utilisateur
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: no content
        '404':
          description: not found
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000
